### ISSUE TITLE
ReferenceError: Cannot access 'status' before initialization

### ISSUE THREAD

**Issue by rizwan92** [vercel/hazel#153]
I am facing this issue 

```
[GET] /update/win32/1.0.0/RELEASES?id=release&localVersion=1.0.0&arch=amd64
23:57:04:08
Caching version v1.0.1...
2022-10-13T18:27:12.134Z	7f077f6e-4b8f-45ee-9cb7-6a2d60edb1b1	ERROR	ReferenceError: Cannot access 'status' before initialization
    at retry.retries (/var/task/lib/cache.js:52:76)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Cache.cacheReleaseList (/var/task/lib/cache.js:46:30)
    at async Cache.refreshCache (/var/task/lib/cache.js:142:40)
    at async Cache.loadCache (/var/task/lib/cache.js:188:7)
    at async exports.releases (/var/task/lib/routes.js:180:20)
Finished caching version v1.0.1

```

![Screenshot 2022-10-13 235358](https://user-images.githubusercontent.com/19162978/195678218-44603fc1-27b0-4458-88e1-8279a3236a4f.png)
![Screenshot 2022-10-14 000133](https://user-images.githubusercontent.com/19162978/195678224-2a3220c4-2350-41fa-965e-e0d17d852622.png)

**Comment by rizwan92** [comment]
i fixed the issue by applying this changes 
![image](https://user-images.githubusercontent.com/19162978/195825578-fa4c0b40-4460-49e8-b3a7-8686dbe3613a.png)

**Comment by rizwan92** [comment]
but the issue is  hazel is trying to download the RELEASE FILE from my private repository release assets to update the windows squirrel framework 
I console log the URL and headers
```
https://github.com/rizwan92/chikupos-software/releases/download/v1.0.1/RELEASES
{
  Accept: 'application/vnd.github.preview',
  Authorization: 'token mytoken'
}
```

status 404 received but when I try to download the file by clicking on the link it is downloading the RELEASE file in my browser.

but I can download my exe and dmg files from hazel UI from this link https://release.chikupos.com/

**Comment by rizwan92** [comment]
i fixed this issue by pulling this commit https://github.com/vercel/hazel/pull/149/commits/b5abe54603b5900b3416992bb5ce2038fcddf198
